services:
  redis:
    image: redis
  mongo:
    image: mongo
  worker:
    image: proteus/worker
    build:
      context: worker/
    volumes:
      - /home/op/.axiom/accounts/personal.json:/root/.axiom/accounts/default.json
      - /home/op/.axiom/modules:/root/.axiom/modules
      - /home/op/.ssh:/root/.ssh
      - /mnt/volume_nyc3_01/docs/proteus:/app
    depends_on:
    - redis
    - mongo
  api:
    image: proteus/api
    build:
      context: api/
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
    - '127.0.0.1:80:80'
    depends_on:
      - redis
